### ISSUE TITLE
limo_test_integration crash

### ISSUE THREAD

**Issue by arnodelorme** [sccn/eeglab-testcases#1]
All jobs have been processed, but some jobs have failed.
You may want to restart the pipeline latter if you managed to fix the problems.
LIMO batch done, some errors where detected see report
LIMO batch works thanks to PSOM by Bellec et al. (2012)
The Pipeline System for Octave and Matlab. Front. Neuroinform. 6:7
Re-saving study file
generating temporary files, pulling relevant trials ... 
making up statistical models ... 
Unrecognized function or variable 'splitreg'.
Unable to resolve the name Model2_files.con.
Unable to resolve the name Model2_files.con.
match frames between subjects ...
gathering data ...
Unable to read file '/expanse/projects/nemar/eeglab-testcases/ds002718/derivatives2/sub-002/eeg/FaceRepetition_GLM_Channels_Time_OLS/con_1.mat'. No such file or directory.
match frames between subjects ...
gathering data ...
Unable to read file '/expanse/projects/nemar/eeglab-testcases/ds002718/derivatives2/sub-002/eeg/FaceRepetition_GLM_Channels_Time_OLS/con_1.mat'. No such file or directory.
3 groups with a maximum of 7 subjects per group
match frames between subjects ...
gathering data ...
Unable to read file '/expanse/projects/nemar/eeglab-testcases/ds002718/derivatives2/sub-002/eeg/FaceRepetition_GLM_Channels_Time_OLS/con_1.mat'. No such file or directory.
3 groups with a maximum of 7 subjects per group
match frames between subjects ...
gathering data ...
Unable to read file '/expanse/projects/nemar/eeglab-testcases/ds002718/derivatives2/sub-002/eeg/FaceRepetition_GLM_Channels_Time_OLS/con_1.mat'. No such file or directory.
match frames between subjects ...
LIMO.Type not found - can't match data across subjects
Warning: test failure - files were not deleted from drive 
Elapsed time is 74.635233 seconds.

**Comment by arnodelorme** [comment]
[fulllog.txt](https://github.com/sccn/eeglab-testcases/files/6026768/fulllog.txt)

**Comment by arnodelorme** [comment]
@CPernet would you mind to have a look. Also I used this file 

https://github.com/sccn/eeglab-testcases/blob/master/unittesting_limo/limo_test_integration.m

I have added some code to create 3 groups and changed the path. No other changes.

**Comment by CPernet** [comment]
I ran it on my PC (with the study change as you - repo updated accordingly);  - all ran without fail which makes me thing the issue is with the data or associated code

test successful --> Elapsed time is 1954.563347 seconds 
limotest'

ans =

  9×1 cell array

    {'categorical design + contrasts with OLS estimates successful'}
    {'mixed design with WLS estimates + contrast successful'       }
    {'one sample t-tests successful'                               }
    {'regressions successful'                                      }
    {'paired t-test successful'                                    }
    {'two samples t-test successful'                               }
    {'1-way ANOVA successful'                                      }
    {'ANCOVA + contrast successful'                                }
    {'Repeated measures ANOVA + contrast successful'               }

data preprocessed  as in https://github.com/LIMO-EEG-Toolbox/limo_meeg/blob/master/resources/from_bids2stats.m

**Comment by CPernet** [comment]
from your report above
Unrecognized function or variable 'splitreg'. 
Unable to resolve the name Model2_files.con.

From your full log 1st FAILED line 5004+
The logical indices in position 2 contain a true value outside of the array bounds.File /expanse/projects/nemar/eeglab/plugins/limo3.0/limo_contrast_checking.m at line 87
File /expanse/projects/nemar/eeglab/plugins/limo3.0/limo_batch_contrast.m at line 17

so the 2nd model 3 faces + continuous seem ok to run, yet the contrast fails because out of bounds??
- looks to me continuous regressors were not loaded (you can check in one subject LIMO.design.X) which would explain why contrast fails
- would explain the 'splitreg' error coming from pop_limo.m

--> so error would be from updating STUDY line 80+ where continuous regressors are not loaded

**Comment by CPernet** [comment]
added a size check in limo_contrast to make error message more explicit

**Comment by CPernet** [comment]
does the updated script from https://github.com/LIMO-EEG-Toolbox/limo_test_stats/blob/master/limo_test_integration.m work?
